# Generated by Django 4.2.6 on 2023-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common', models.CharField(max_length=80)),
                ('official', models.CharField(max_length=80)),
                ('capital', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=80)),
                ('subregion', models.CharField(blank=True, max_length=80, null=True)),
                ('flag', models.CharField(max_length=250)),
                ('maps', models.CharField(max_length=250)),
            ],
        ),
    ]
